# Generated by Django 5.0.7 on 2024-08-11 17:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('body', models.TextField(blank=True, null=True)),
                ('colors', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=50)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.board')),
            ],
        ),
    ]
