# Generated by Django 5.0.7 on 2024-08-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_board_user_alter_note_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
